### ISSUE TITLE
Condition Lab does not work in 0.8.6 with pf2e system

### ISSUE THREAD

**Issue by Ghilteras** [death-save/combat-utility-belt#540]
when I click on Condition Lab I get this error in the console

```
foundry.js:2005 TypeError: An error occurred while rendering ConditionLab 183: conditionMap.forEach is not a function
    at ConditionLab.prepareData (condition-lab.js:125)
    at async ConditionLab._render (foundry.js:2041)
    at async ConditionLab._render (foundry.js:2728)
```
